// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZn-gESPHezI_yw8ErUwvZ01IhYAbNQwE',
    appId: '1:1048498203227:web:1bd6a9cb61948462056d7e',
    messagingSenderId: '1048498203227',
    projectId: 'promising-node-365522',
    authDomain: 'promising-node-365522.firebaseapp.com',
    storageBucket: 'promising-node-365522.appspot.com',
    measurementId: 'G-DNT2YYC3KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnfpbMd3kVnuc4AXBS5vSVCRVSWrH9yec',
    appId: '1:1048498203227:android:d54c1b92c3e2e6dd056d7e',
    messagingSenderId: '1048498203227',
    projectId: 'promising-node-365522',
    storageBucket: 'promising-node-365522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnIXpm9CWx1-JSGsUten9qehCUNmUbPHw',
    appId: '1:1048498203227:ios:0a3156241c063d51056d7e',
    messagingSenderId: '1048498203227',
    projectId: 'promising-node-365522',
    storageBucket: 'promising-node-365522.appspot.com',
    iosClientId: '1048498203227-t1hn1004okmf9uch1o6pt8i9kh0d4mcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnIXpm9CWx1-JSGsUten9qehCUNmUbPHw',
    appId: '1:1048498203227:ios:0a3156241c063d51056d7e',
    messagingSenderId: '1048498203227',
    projectId: 'promising-node-365522',
    storageBucket: 'promising-node-365522.appspot.com',
    iosClientId: '1048498203227-t1hn1004okmf9uch1o6pt8i9kh0d4mcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
